-- MySQL Script generated by MySQL Workbench
-- Tue Jun 28 11:39:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ciifen
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ciifen
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ciifen` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ciifen` ;

-- -----------------------------------------------------
-- Table `ciifen`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciifen`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` CHAR(10) NULL DEFAULT NULL,
  `correo` CHAR(100) NULL DEFAULT NULL,
  `contraseña` CHAR(12) NULL DEFAULT NULL,
  `tipo_usuario` CHAR(30) NULL DEFAULT NULL,
  `estado` TINYINT(1) NULL DEFAULT NULL,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ciifen`.`mantenimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciifen`.`mantenimiento` (
  `id_mantenimiento` INT NOT NULL,
  `tipo_mantenimiento` CHAR(30) NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `detalle` CHAR(200) NULL DEFAULT NULL,
  `usuarioCreador` INT NULL DEFAULT NULL,
  `estado` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id_mantenimiento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ciifen`.`instrumento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciifen`.`instrumento` (
  `id_instrumento` INT NOT NULL,
  `codigo` CHAR(13) NULL DEFAULT NULL,
  `tipo` CHAR(30) NULL DEFAULT NULL,
  `marca` CHAR(30) NULL DEFAULT NULL,
  `modelo` CHAR(30) NULL DEFAULT NULL,
  `serialInstrumento` CHAR(30) NULL DEFAULT NULL,
  `usuarioCreador` INT NULL DEFAULT NULL,
  `id_mantenimiento` INT NULL DEFAULT NULL,
  `estado` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id_instrumento`),
  INDEX `id_mantenimiento` (`id_mantenimiento` ASC) VISIBLE,
  CONSTRAINT `instrumento_ibfk_1`
    FOREIGN KEY (`id_mantenimiento`)
    REFERENCES `ciifen`.`mantenimiento` (`id_mantenimiento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ciifen`.`estacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciifen`.`estacion` (
  `id_estacion` VARCHAR(10) NOT NULL,
  `nombre` CHAR(100) NULL DEFAULT NULL,
  `altitud` DOUBLE NULL DEFAULT NULL,
  `latitud` DOUBLE NULL DEFAULT NULL,
  `longitud` DOUBLE NULL DEFAULT NULL,
  `estado` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id_estacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ciifen`.`pluviograma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciifen`.`pluviograma` (
  `id_pluviograma` VARCHAR(10) NOT NULL,
  `imagen` BLOB NULL DEFAULT NULL,
  `Fecha_inicio` DATE NULL DEFAULT NULL,
  `Fecha_Fin` DATE NULL DEFAULT NULL,
  `Fecha_digitalizacion` DATE NULL DEFAULT NULL,
  `Modelo` CHAR(30) NULL DEFAULT NULL,
  `Ruta` CHAR(30) NULL DEFAULT NULL,
  `Estado` TINYINT(1) NULL DEFAULT NULL,
  `id_estacion` VARCHAR(10) NULL DEFAULT NULL,
  `id_instrumento` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_pluviograma`),
  INDEX `id_instrumento` (`id_instrumento` ASC) VISIBLE,
  INDEX `id_estacion` (`id_estacion` ASC) VISIBLE,
  CONSTRAINT `pluviograma_ibfk_1`
    FOREIGN KEY (`id_instrumento`)
    REFERENCES `ciifen`.`instrumento` (`id_instrumento`),
  CONSTRAINT `pluviograma_ibfk_2`
    FOREIGN KEY (`id_estacion`)
    REFERENCES `ciifen`.`estacion` (`id_estacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ciifen`.`actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciifen`.`actividad` (
  `id_actividad` INT NOT NULL,
  `tipoActividad` CHAR(30) NULL DEFAULT NULL,
  `fechaActividad` DATE NULL DEFAULT NULL,
  `id_usuario` INT NULL DEFAULT NULL,
  `id_pluviograma` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id_actividad`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `id_pluviograma` (`id_pluviograma` ASC) VISIBLE,
  CONSTRAINT `actividad_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ciifen`.`usuario` (`id_usuario`),
  CONSTRAINT `actividad_ibfk_2`
    FOREIGN KEY (`id_pluviograma`)
    REFERENCES `ciifen`.`pluviograma` (`id_pluviograma`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ciifen`.`datos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciifen`.`datos` (
  `id_datos` INT NOT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `hora` TIME NULL DEFAULT NULL,
  `precipitacion` DOUBLE NULL DEFAULT NULL,
  `estado` TINYINT(1) NULL DEFAULT NULL,
  `id_pluviograma` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id_datos`),
  INDEX `id_pluviograma` (`id_pluviograma` ASC) VISIBLE,
  CONSTRAINT `datos_ibfk_1`
    FOREIGN KEY (`id_pluviograma`)
    REFERENCES `ciifen`.`pluviograma` (`id_pluviograma`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ciifen`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciifen`.`persona` (
  `id_persona` INT NOT NULL,
  `cedula` CHAR(13) NULL DEFAULT NULL,
  `nombre` CHAR(100) NULL DEFAULT NULL,
  `apellido` CHAR(100) NULL DEFAULT NULL,
  `correo` CHAR(100) NULL DEFAULT NULL,
  `direccion` CHAR(100) NULL DEFAULT NULL,
  `id_usuario` INT NULL DEFAULT NULL,
  `estado` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id_persona`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `persona_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ciifen`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ciifen`.`telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciifen`.`telefono` (
  `id_telefono` INT NOT NULL,
  `contacto` INT NULL DEFAULT NULL,
  `telefono` CHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id_telefono`),
  INDEX `contacto` (`contacto` ASC) VISIBLE,
  CONSTRAINT `telefono_ibfk_1`
    FOREIGN KEY (`contacto`)
    REFERENCES `ciifen`.`persona` (`id_persona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ciifen`.`trazabilidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciifen`.`trazabilidad` (
  `id_registro` INT NOT NULL,
  `valor_anterior` CHAR(100) NULL DEFAULT NULL,
  `usuarioModificado` INT NULL DEFAULT NULL,
  `fechaModificacion` DATE NULL DEFAULT NULL,
  `detalle` CHAR(200) NULL DEFAULT NULL,
  `usuarioCreador` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_registro`),
  INDEX `usuarioCreador` (`usuarioCreador` ASC) VISIBLE,
  CONSTRAINT `trazabilidad_ibfk_1`
    FOREIGN KEY (`usuarioCreador`)
    REFERENCES `ciifen`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
