DROP DATABASE CIIFEN;
-- MySQL Script generated by MySQL Workbench
-- Tue Jun 28 11:39:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ciifen
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ciifen
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ciifen` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ciifen` ;

-- -----------------------------------------------------
-- Table `ciifen`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciifen`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT ,
  `usuario` CHAR(10) NULL DEFAULT NULL UNIQUE,
  `correo` CHAR(100) NULL DEFAULT NULL,
  `contraseña` CHAR(100) NULL DEFAULT NULL,
  `nombre` CHAR(100) NULL DEFAULT NULL,
  `tipo_usuario` CHAR(30) NULL DEFAULT NULL,
  `estado` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ciifen`.`modelo`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `ciifen`.`modelo` (
  `id_modelo` INT NOT NULL AUTO_INCREMENT ,
  `nombre` CHAR(100) NULL DEFAULT NULL UNIQUE,
  `tiempo_min` TIME NULL DEFAULT NULL,
  `tiempo_max` TIME NULL DEFAULT NULL,
  `precipitacion_min` FLOAT NULL DEFAULT NULL,
  `precipitacion_max` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id_modelo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `ciifen`.`estacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciifen`.`estacion` (
  `id_estacion` VARCHAR(10) NOT NULL,
  `nombre` CHAR(100) NULL DEFAULT NULL,
  `altitud` DOUBLE NULL DEFAULT NULL,
  `latitud` DOUBLE NULL DEFAULT NULL,
  `longitud` DOUBLE NULL DEFAULT NULL,
  `estado` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id_estacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ciifen`.`pluviograma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciifen`.`pluviograma` (
  `id_pluviograma` VARCHAR(100) NOT NULL,
  `imagen` BLOB NULL DEFAULT NULL,
  `Fecha_inicio` DATE NULL DEFAULT NULL,
  `Fecha_Fin` DATE NULL DEFAULT NULL,
  `Fecha_digitalizacion` DATE NULL DEFAULT NULL,
  `Modelo` CHAR(30) NULL DEFAULT NULL,
  `Ruta` CHAR(30) NULL DEFAULT NULL,
  `Estado` TINYINT(1) NULL DEFAULT NULL,
  `id_estacion` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id_pluviograma`),
  INDEX `id_estacion` (`id_estacion` ASC) VISIBLE,
  CONSTRAINT `pluviograma_ibfk_2`
    FOREIGN KEY (`id_estacion`)
    REFERENCES `ciifen`.`estacion` (`id_estacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
